on:
  push:
    branches: [main]
name: CI

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2

    - name: Install packages
      run: npm ci

    - name: Clean & Build
      run: |
        npm run clean
        npm run build

    - name: Deploy to gh-pages
      shell: bash
      run: |
        git -C public init -q
        git -C public remote add origin "$(git remote get-url origin)"
        git -C public fetch origin gh-pages:gh-pages
        git -C public config credential.helper "$(git config credential.helper)"
        git -C public config 'http.https://github.com/.extraheader' "$(git config 'http.https://github.com/.extraheader')"
        git -C public config core.autocrlf input
        git -C public config core.safecrlf false
        git -C public symbolic-ref HEAD refs/heads/gh-pages
        git -C public reset
        git -C public add -A
        if git -C public -c 'user.name=github-actions[bot]' -c 'user.email=41898282+github-actions[bot]@users.noreply.github.com' \
          commit -m "Deploy $(date -I) $(git rev-parse HEAD)";
        then
          git -C public push -u origin gh-pages --quiet
        else
          echo 'No changes to commit'
        fi
