on:
    push:
        branches:
            - dev
            - main
    pull_request:
name: CI

jobs:
    pre_job:
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5.3.1
              with:
                  cancel_others: 'true'

    check:
        name: Checks
        needs: pre_job
        if: ${{ github.ref == 'refs/heads/dev' || needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - run: pnpm install
            - run: pnpm run lint
            - run: pnpm run check

    test_unit:
        name: Unit Tests
        needs: pre_job
        if: ${{ github.ref == 'refs/heads/dev' || needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - run: pnpm install
            - run: pnpm run test:unit

    test_e2e:
        name: E2E Tests
        needs: pre_job
        if: ${{ github.ref == 'refs/heads/dev' || needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - run: pnpm install

            - name: Install Playwright Browsers
              run: pnpm --filter=web exec playwright install --with-deps

            - run: pnpm run test:e2e

            - name: Upload Playwright report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: packages/web/playwright-report/
                  retention-days: 14

    build_deploy:
        name: Build & Deploy
        needs: pre_job
        if: ${{ github.ref == 'refs/heads/dev' || needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - run: pnpm install

            - name: Build
              run: SUDOKU_STUDIO_VERSION="${GITHUB_SHA:0:7}" pnpm run build

            - name: Deploy to gh-pages
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
              shell: bash
              run: |
                  BASE_DIR=packages/web/build
                  touch "$BASE_DIR/.nojekyll"
                  git -C "$BASE_DIR" init -q
                  git -C "$BASE_DIR" remote add origin "$(git remote get-url origin)"
                  git -C "$BASE_DIR" fetch origin gh-pages:gh-pages
                  git -C "$BASE_DIR" config credential.helper "$(git config credential.helper)"
                  git -C "$BASE_DIR" config 'http.https://github.com/.extraheader' "$(git config 'http.https://github.com/.extraheader')"
                  git -C "$BASE_DIR" config core.autocrlf input
                  git -C "$BASE_DIR" config core.safecrlf false
                  git -C "$BASE_DIR" symbolic-ref HEAD refs/heads/gh-pages
                  git -C "$BASE_DIR" reset
                  git -C "$BASE_DIR" add -A
                  if git -C "$BASE_DIR" -c 'user.name=github-actions[bot]' -c 'user.email=41898282+github-actions[bot]@users.noreply.github.com' \
                    commit -m "Deploy $(date -I) $(git rev-parse HEAD)";
                  then
                    git -C "$BASE_DIR" push -u origin gh-pages --quiet
                  else
                    echo 'No changes to commit'
                  fi
